services:
  app:
    image: backend-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: backend-dev
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: bun run --watch src/index.ts
